/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package gal.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KEY = 5;
  /** RegularExpression Id. */
  int CONDITION = 6;
  /** RegularExpression Id. */
  int ACTION = 7;
  /** RegularExpression Id. */
  int SPECIAL_KEY = 8;
  /** RegularExpression Id. */
  int DIRVAR = 9;
  /** RegularExpression Id. */
  int CATVAR = 10;
  /** RegularExpression Id. */
  int DIRECTION = 11;
  /** RegularExpression Id. */
  int CATEGORY = 12;
  /** RegularExpression Id. */
  int MOUSE = 13;
  /** RegularExpression Id. */
  int UNDERSCORE = 14;
  /** RegularExpression Id. */
  int CAPITAL = 15;
  /** RegularExpression Id. */
  int LOWERCASE = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int UNARY = 19;
  /** RegularExpression Id. */
  int CONJUNCTION = 20;
  /** RegularExpression Id. */
  int DISJUNCTION = 21;
  /** RegularExpression Id. */
  int SEQUENCE = 22;
  /** RegularExpression Id. */
  int ID = 23;
  /** RegularExpression Id. */
  int INTEGER = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"Key\"",
    "<CONDITION>",
    "<ACTION>",
    "<SPECIAL_KEY>",
    "\"d\"",
    "<CATVAR>",
    "<DIRECTION>",
    "<CATEGORY>",
    "<MOUSE>",
    "\"_\"",
    "<CAPITAL>",
    "<LOWERCASE>",
    "<LETTER>",
    "<DIGIT>",
    "\"!\"",
    "\"&\"",
    "\"/\"",
    "\";\"",
    "<ID>",
    "<INTEGER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"*\"",
    "\":\"",
    "\"|\"",
    "\"?\"",
    "\"%\"",
    "\",\"",
  };

}
